import React, { createContext, useContext, useEffect, useMemo, useState } from "react";

export const STRINGS = {
  en: {
    brand: "TeleDentAI",
    nav: { home: "Home", how: "How it works", capture: "Start diagnosis", results: "Results", chat: "Doctor chat", about: "About" },
    hero: {
      title1: "Your Child's Smile",
      title2: "Deserves Early Care",
      title3: "",
      mainHeadline: "Your Child's Smile Deserves Early Care",
      subtitle: "AI dental screening in minutes. Detect cavities and issues before they become problems.",
      cta1: "Start Diagnosis",
      cta2: "Learn More",
      about: "About",
    },
    features: {
      why: "Why Choose Our AI Diagnostics?",
      f1: "Expert Validated",
      f1d: "AI model trained and validated by dental professionals",
      f2: "Quick Results",
      f2d: "Get instant analysis results in minutes, not days",
      f3: "Secure & Private",
      f3d: "Your dental images and data are encrypted and protected",
      f4: "AI-Powered Analysis",
      f4d: "Advanced machine learning algorithms for accurate dental diagnostics",
      ready: "Ready to Check Your Dental Health",
      ready_d: "Take the first step towards better dental health with our AI-powered diagnostic tool.",
      get_started: "Get Started Now",
    },
    how: {
      title: "How It Works",
      subtitle: "Follow these simple steps to get your dental health assessment",
      s1: "Take 5 photos of your teeth from different angles",
      s1Title: "Capture Images",
      s2: "Our AI analyzes the images for signs of decay",
      s2Title: "AI Analysis",
      s3: "Get instant results with highlighted problem areas",
      s3Title: "View Results",
      s4: "Receive recommendations for next steps",
      s4Title: "Consult Expert",
      notesTitle: "Important Notes",
      notesSubtitle: "Keep these important points in mind for best results",
      n1: "This is a diagnostic aid tool, not a replacement for professional dental care",
      n2: "All images are processed locally and securely deleted after analysis",
      n3: "Results should be confirmed with a qualified dentist",
      n4: "The examination takes approximately 2–3 minutes",
      whyChoose: "Why Choose AI Dental Analysis?",
      benefit1: "Instant Results",
      benefit1Desc: "Get your dental health assessment in minutes, not days",
      benefit2: "Secure & Private",
      benefit2Desc: "Your data is encrypted and HIPAA compliant",
      benefit3: "Cost Effective",
      benefit3Desc: "Affordable screening before expensive procedures",
      benefit4: "High Accuracy",
      benefit4Desc: "AI trained on thousands of dental images",
      back: "Back to Home",
      start: "Start Examination",
    },
    capture: {
      title: "Photo Collection",
      subtitle: "Capture images from 5 different angles for comprehensive AI analysis",
      current: "Current:",
      tips: "Tips for Front View",
      tipsText: "Smile showing front teeth, ensure good lighting, and keep the camera steady.",
      upload: "Upload file",
      startCam: "Start Camera",
      snap: "Capture",
      replace: "Replace",
      next: "Next: See Results",
      selectView: "Select View",
      noPreview: "No preview available",
      startCameraOrUpload: "Start camera or upload an image",
      views: {
        front: "Front View",
        left: "Left Side",
        right: "Right Side",
        upper: "Upper Teeth",
        lower: "Lower Teeth",
      },
      viewTips: {
        front: {
          tips: "Tips for Front View",
          tipsText: "Smile showing front teeth, ensure good lighting, and keep the camera steady."
        },
        left: {
          tips: "Tips for Left View",
          tipsText: "Turn your head slightly to show the left side teeth clearly, ensure even lighting."
        },
        right: {
          tips: "Tips for Right View",
          tipsText: "Turn your head slightly to show the right side teeth clearly, avoid shadowed areas."
        },
        upper: {
          tips: "Tips for Upper View",
          tipsText: "Tilt your head back to show the upper teeth clearly, keep your mouth open naturally."
        },
        lower: {
          tips: "Tips for Lower View",
          tipsText: "Tilt your head down to show the lower teeth, ensure lighting covers the full area."
        }
      },
      // ==================================================================================
      // i18n: New translations for image validation and progress tracking
      // Added for 5-image requirement and progress UI
      // ==================================================================================
      progress: "Progress",
      of: "of",
      imagesCaptured: "images captured",
      allReady: "All images ready!",
      pleaseCapture: "Please capture all",
      viewsText: "views",
      warning: "Please capture all",
      beforeProceeding: "views before proceeding to analysis.",
      missing: "Missing",
      images: "image(s)",
      captureFirst: "Capture All",
      imagesFirst: "Images First",
      analyzeAll: "Analyze All",
      imagesBtn: "Images",
      alertMessage: "Please capture all {0} images before proceeding.\nCurrently captured: {1}",
      captured: "Captured",
      notCaptured: "Not captured",
      saved: "Saved",
    },
    results: {
      title: "Preliminary Results",
      sub: "Here's a quick summary based on your photos. For medical decisions, consult a dentist.",
      status_ok: "Low risk detected. Keep regular hygiene.",
      status_warn: "Potential enamel issues found. Consider a professional check.",
      manage: "Do you want to manage communication with a doctor?",
      consultDesc: "Discuss your results with an expert dentist",
      goChat: "Open chat with a dentist",
      // ==================================================================================
      // i18n: New translations for AI processing and results display
      // Added for enhanced loading states and detection results
      // ==================================================================================
      aiAnalysisInProgress: "AI Analysis in Progress",
      processingImages: "Processing your dental images with advanced AI detection...",
      currentlyProcessing: "Currently processing:",
      view: "view",
      loadingImages: "Loading images",
      detectingConditions: "Detecting conditions",
      generatingReport: "Generating report",
      usuallyTakes: "This usually takes 5-15 seconds depending on your connection",
      error: "Error",
      errorMessage: "Cannot connect to AI server. Please make sure the FastAPI server is running.",
      startServer: "To start the AI server:",
      navigateFolder: "Navigate to the Integration folder",
      runCommand: "Run:",
      waitStartup: "Wait for \"Application startup complete\"",
      refreshPage: "Refresh this page",
      backToCapture: "Back to Capture",
      aiServer: "AI Server:",
      connected: "Connected",
      disconnected: "Disconnected",
      issuesDetected: "potential issue(s) detected",
      reviewResults: "Please review the detailed results below and consult with a dentist.",
      noIssuesAll: "No issues detected in this view",
      detailedAnalysis: "Detailed Analysis by View",
      originalImage: "Original Image:",
      aiAnalysis: "AI Analysis (with detections marked):",
      detectedConditions: "Detected Conditions:",
      confidence: "Confidence:",
      errorProcessing: "Error processing this image:",
      retakeImages: "Retake Images",
      discussAI: "Discuss with a Dentist",
      analyzingView: "Analyzing {0} view... ({1}/{2})",
      startingAnalysis: "Starting AI analysis of {0} images...",
      noImages: "No images to process. Please capture images first.",
      noImagesFound: "No images found. Please capture images first.",
      failedLoad: "Failed to load images. Please try capturing again.",
    },
    chat: {
      title: "Professional Dental Consultation",
      subtitle: "Discuss your results with our qualified dental professionals",
      placeholder: "Type your message…",
      send: "Send",
      back: "Back to results",
      welcome: "Hello, I'm Dr. Ahmed. I can help review your results and answer any questions you have about your dental health.",
      response: "Thanks for sharing. Can you describe any pain, sensitivity, or other symptoms you're experiencing?",
      online: "Online",
      suggestion1: "What do these results mean?",
      suggestion2: "Should I see a dentist?",
      suggestion3: "What treatments are available?",
    },
    footer: {
      quickLinks: "Quick Links",
      contact: "Contact",
      support: "yazeedjonsh@gmail.com",
      phone: "+966 50 032 3405",
      rights: "All rights reserved.",
      privacy: "Privacy Policy",
      terms: "Terms of Service",
    },
    langToggle: "العربية",
  },
   ar: {
    brand: "TeledenAI",
    nav: { home: "الرئيسية", how: "كيف يعمل", capture: "بدء التشخيص", results: "النتائج", chat: "المحادثة", about: "عن المشروع" },
    hero: {
      title1: "ابتسامة طفلك",
      title2: "تستحق الرعاية المبكرة",
      title3: "",
      mainHeadline: "ابتسامة طفلك تستحق الرعاية المبكرة",
      subtitle: "تشخيص الأسنان بالذكاء الاصطناعي في دقائق. اكتشف التسوس والمشاكل الأخرى قبل تفاقمها.",
      cta1: "ابدأ التشخيص",
      cta2: "اعرف أكثر",
    },
    features: {
      why: "لماذا تختار تشخيصنا بالذكاء الاصطناعي؟",
      f1: "موثَّق من خبراء",
      f1d: "نموذج معتمَد تم تدريبه والتحقق منه من مختصّي طب الأسنان",
      f2: "نتائج سريعة",
      f2d: "تحليل فوري خلال دقائق بدلًا من أيام",
      f3: "آمن وخصوصي",
      f3d: "صورك وبياناتك مُشفّرة ومحميّة",
      f4: "تحليل بالذكاء الاصطناعي",
      f4d: "خوارزميات متقدمة لتشخيص دقيق",
      ready: "جاهز لفحص صحة أسنانك؟",
      ready_d: "ابدأ أول خطوة نحو صحة فموية أفضل عبر أداتنا الذكية.",
      get_started: "ابدأ الآن",
    },
    how: {
      title: "كيف يعمل",
      subtitle: "اتبع هذه الخطوات البسيطة للحصول على أفضل نتيجة",
      s1: "التقط 5 صور لأسنانك من زوايا مختلفة",
      s1Title: "التقط الصور",
      s2: "يقوم الذكاء الاصطناعي بتحليل الصور للكشف عن المشاكل",
      s2Title: "تحليل الذكاء الاصطناعي",
      s3: "احصل على نتائج فورية مع إبراز مناطق الاشتباه",
      s3Title: "عرض النتائج",
      s4: "استلم توصيات واضحة للخطوات التالية",
      s4Title: "استشارة خبير",
      notesTitle: "ملاحظات مهمة",
      notesSubtitle: "راجع هذه النقاط المهمة قبل البدء للحصول على أفضل النتائج",
      n1: "هذه أداة مساعدة وليست بديلًا عن زيارة الطبيب",
      n2: "تُعالَج الصور محليًا وتُحذف بأمان بعد التحليل",
      n3: "يجب تأكيد النتائج مع طبيب أسنان مختص",
      n4: "يستغرق الفحص قرابة دقيقتين إلى ثلاث دقائق",
      whyChoose: "لماذا تختار تشخيصنا بالذكاء الاصطناعي؟",
      benefit1: "نتائج فورية",
      benefit1Desc: "احصل على تشخيص صحة أسنانك في دقائق،",
      benefit2: "آمن وسري",
      benefit2Desc: "بياناتك مشفرة ومتوافقة مع HIPAA",
      benefit3: "اقتصادي وميسر",
      benefit3Desc: "فحص ميسور التكلفة قبل الإجراءات المكلفة",
      benefit4: "دقة عالية",
      benefit4Desc: "ذكاء اصطناعي مدرب على آلاف صور الأسنان",
      back: "العودة للرئيسية",
      start: "ابدأ التشخيص",
    },
    capture: {
      title: "تجميع الصور",
      subtitle: "التقط صوراً من 5 زوايا مختلفة للكشف عن المشاكل بالذكاء الاصطناعي",
      current: "المحدّد الآن:",
      tips: "نصائح للواجهة الأمامية",
      tipsText: "ابتسم مع إظهار الأسنان الأمامية، واحرص على إضاءة جيدة وثبات الكاميرا.",
      upload: "رفع ملف",
      startCam: "تشغيل الكاميرا",
      snap: "التقاط",
      replace: "استبدال",
      next: "التالي: عرض النتائج",
      selectView: "اختر الزاوية",
      noPreview: "لا توجد معاينة متاحة",
      startCameraOrUpload: "ابدأ الكاميرا أو ارفع صورة",
      views: {
        front: "الواجهة الأمامية",
        left: "الجانب الأيسر",
        right: "الجانب الأيمن",
        upper: "الأسنان العلوية",
        lower: "الأسنان السفلية",
      },
      viewTips: {
        front: {
          tips: "نصائح للواجهة الأمامية",
          tipsText: "ابتسم مع إظهار الأسنان الأمامية، واحرص على إضاءة جيدة وثبات الكاميرا."
        },
        left: {
          tips: "نصائح للجانب الأيسر",
          tipsText: "أدِر رأسك قليلاً لإظهار الأسنان الجانبية اليسرى بوضوح، وتأكد من الإضاءة المتساوية."
        },
        right: {
          tips: "نصائح للجانب الأيمن",
          tipsText: "أدِر رأسك قليلاً لإظهار الأسنان الجانبية اليمنى بوضوح، وتجنب المناطق الظليلة."
        },
        upper: {
          tips: "نصائح للأسنان العلوية",
          tipsText: "أمِل رأسك للخلف لإظهار الأسنان العلوية بوضوح، وأبقِ فمك مفتوحاً بشكل طبيعي."
        },
        lower: {
          tips: "نصائح للأسنان السفلية",
          tipsText: "أمِل رأسك للأسفل لإظهار الأسنان السفلية، وتأكد من أن الإضاءة تغطي المنطقة بالكامل."
        }
      },
      // ==================================================================================
      // i18n: الترجمة العربية للتحقق من الصور وتتبع التقدم
      // تمت الإضافة لمتطلب 5 صور وواجهة التقدم
      // ==================================================================================
      progress: "التقدم",
      of: "من",
      imagesCaptured: "صورة تم التقاطها",
      allReady: "جميع الصور جاهزة!",
      pleaseCapture: "يرجى التقاط كل",
      viewsText: "الزوايا",
      warning: "يرجى التقاط كل",
      beforeProceeding: "الزوايا قبل المتابعة للتحليل.",
      missing: "متبقي",
      images: "صورة",
      captureFirst: "التقط كل",
      imagesFirst: "الصور أولاً",
      analyzeAll: "تحليل كل",
      imagesBtn: "الصور",
      alertMessage: "يرجى التقاط جميع الصور الـ {0} قبل المتابعة.\nتم التقاط: {1}",
      captured: "تم الالتقاط",
      notCaptured: "لم تُلتقط",
      saved: "تم الحفظ",
    },
    results: {
      title: "نتائج أولية",
      sub: "هذا ملخص سريع اعتمادًا على صورك. للقرارات الطبية، يُنصح بمراجعة طبيب أسنان.",
      status_ok: "مخاطر منخفضة، استمر بالعناية اليومية.",
      status_warn: "اشتباه بمشكلات في الاسنان، يُفضَّل الفحص لدى طبيب.",
      manage: "هل تريد بدء مع طبيب؟",
      consultDesc: "ناقش نتائجك مع طبيب أسنان خبير",
      goChat: "افتح محادثة مع طبيب",
      aiAnalysisInProgress: "تشخيص الذكاء الاصطناعي قيد التنفيذ",
      processingImages: "جارٍ معالجة صور أسنانك باستخدام الذكاء الاصطناعي...",
      currentlyProcessing: "جارٍ المعالجة الآن:",
      view: "الزاوية",
      loadingImages: "تحميل الصور",
      detectingConditions: "كشف الحالات",
      generatingReport: "إنشاء التقرير",
      usuallyTakes: "يستغرق هذا عادةً دقيقة الى دقيقتين حسب سرعة اتصالك",
      error: "خطأ",
      errorMessage: "تعذر الاتصال بخادم الذكاء الاصطناعي. يرجى التأكد من تشغيل خادم FastAPI.",
      startServer: "لبدء خادم الذكاء الاصطناعي:",
      navigateFolder: "انتقل إلى مجلد Integration",
      runCommand: "قم بتشغيل:",
      waitStartup: "انتظر \"Application startup complete\"",
      refreshPage: "قم بتحديث هذه الصفحة",
      backToCapture: "العودة للالتقاط",
      aiServer: "خادم الذكاء الاصطناعي:",
      connected: "متصل",
      disconnected: "غير متصل",
      issuesDetected: "مشاكل محتملة تم اكتشافها",
      reviewResults: "يرجى مراجعة النتائج التفصيلية أدناه واستشارة طبيب أسنان.",
      noIssuesAll: "لم يتم اكتشاف مشاكل في هذه الزاوية",
      detailedAnalysis: "تحليل تفصيلي لكل زاوية",
      originalImage: "الصورة الأصلية:",
      aiAnalysis: "تحليل الذكاء الاصطناعي (مع علامات الكشف):",
      detectedConditions: "الحالات المكتشفة:",
      confidence: "الثقة:",
      errorProcessing: "خطأ في معالجة هذه الصورة:",
      retakeImages: "إعادة التقاط الصور",
      discussAI: "تواصل مع طبيب أسنان",
      analyzingView: "تحليل زاوية {0}... ({1}/{2})",
      startingAnalysis: "بدء تحليل الذكاء الاصطناعي لـ {0} صور...",
      noImages: "لا توجد صور للمعالجة. يرجى التقاط الصور أولاً.",
      noImagesFound: "لم يتم العثور على صور. يرجى التقاط الصور أولاً.",
      failedLoad: "فشل تحميل الصور. يرجى المحاولة مرة أخرى.",
    },
    chat: {
      title: "محادثة مع طبيب",
      subtitle: "ناقش نتائجك مع مساعد الأسنان بالذكاء الاصطناعي",
      placeholder: "اكتب رسالتك…",
      send: "إرسال",
      back: "عودة للنتائج",
      welcome: "مرحباً، أنا د. أحمد. يمكنني مساعدتك في مراجعة نتائجك والإجابة على أي أسئلة لديك حول صحة أسنانك.",
      response: "شكراً لمشاركتك. هل يمكنك وصف أي ألم أو حساسية أو أعراض أخرى تشعر بها؟",
      online: "متصل",
      suggestion1: "ما معنى هذه النتائج؟",
      suggestion2: "هل يجب أن أراجع طبيب أسنان؟",
      suggestion3: "ما الذي يجب علي أن أفعله الآن؟",
    },
    footer: {
      quickLinks: "روابط سريعة",
      contact: "اتصل بنا",
      support: "yazeedjonsh@gmail.com",
      phone: "+966 50 032 3405",
      rights: "جميع الحقوق محفوظة.",
      privacy: "سياسة الخصوصية",
      terms: "شروط الخدمة",
    },
    langToggle: "English",
  },

};

const LangCtx = createContext({ lang: "en", dir: "ltr", t: (k) => k, setLang: () => {} });

export function LangProvider({ children }) {
  const [lang, setLang] = useState(localStorage.getItem("lang") || "en");
  useEffect(() => localStorage.setItem("lang", lang), [lang]);
  const dir = lang === "ar" ? "rtl" : "ltr";
  const t = useMemo(() => {
    const dict = STRINGS[lang];
    return (key) => key.split(".").reduce((a, c) => (a ? a[c] : undefined), dict) ?? key;
  }, [lang]);
  return (
    <LangCtx.Provider value={{ lang, dir, t, setLang }}>
      <div dir={dir} className="min-h-screen bg-gray-50 text-gray-900">{children}</div>
    </LangCtx.Provider>
  );
}

export const useI18n = () => useContext(LangCtx);
